#!/bin/php
<?php
require_once __DIR__.'/vendor/autoload.php';

use Dotenv\Dotenv;
use Symfony\Component\Console\Application;
use BrosSquad\Linker\Api\Console\GenKeyCommand;
use BrosSquad\Linker\Api\Console\GenAppKeyCommand;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

$app = new Application();

/** @var \Psr\Container\ContainerInterface $container */
$container = require __DIR__.'/src/config/dependency_container.php';

$app->addCommands(
    [
        $container->get(GenKeyCommand::class),
        $container->get(GenAppKeyCommand::class),
    ]
);

try {
    $app->run();
} catch (Exception $e) {
    echo $e->getMessage().PHP_EOL;
}
